### ISSUE TITLE
首頁搜尋 "中央投資" 或其統編 "03064421" 均跳出 404 Error

### ISSUE THREAD

**Issue by WeiChengLiou** [solring/twcom_front#5]

**Comment by solring** [comment]
已部分解決
但使用統一編號查詢部分
因為API只能用統編查“d3圖”和“董監事名單”
所以沒辦法顯示名字XD
可能在查董監事名單API那邊再多回傳公司名稱？

**Comment by dustinul6** [comment]
辛苦了這裡的contributors,
不過現在好像不管搜尋什麼都是：
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
如果能修正就太棒了，謝謝！

**Comment by solring** [comment]
已修正！感謝提醒～～～～

**Comment by solring** [comment]
先close
workround的部分另開issue
